"""add owner_user_id to organisations

Revision ID: 2aa3fef6582c
Revises: 34430b459687
Create Date: 2026-08-26 15:53:41.716629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2aa3fef6582c'
down_revision = '34430b459687'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organisations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_organisations_owner_user_id_users', 'users', ['owner_user_id'], ['user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organisations', schema=None) as batch_op:
                batch_op.drop_constraint('fk_organisations_owner_user_id_users', type_='foreignkey')
                batch_op.drop_column('owner_user_id')

    # ### end Alembic commands ###
