"""add avatar_url, app settings, chats, deliveries, and non-financial donation tables

Revision ID: 69b0effaef6d
Revises: e4f5a6b7c8d9
Create Date: 2026-09-03 22:55:06.875702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69b0effaef6d'
down_revision = 'e4f5a6b7c8d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('programs', schema=None) as batch_op:
        batch_op.alter_column('organisation_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('program_kind',
               existing_type=sa.VARCHAR(length=30),
               nullable=False,
               existing_server_default=sa.text("'financial'::character varying"))
        batch_op.alter_column('progress_value',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.create_foreign_key("fk_programs_created_by_users", 'users', ['created_by'], ['user_id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('avatar_url')

    with op.batch_alter_table('programs', schema=None) as batch_op:
        batch_op.drop_constraint("fk_programs_created_by_users", type_='foreignkey')
        batch_op.alter_column('progress_value',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('program_kind',
               existing_type=sa.VARCHAR(length=30),
               nullable=True,
               existing_server_default=sa.text("'financial'::character varying"))
        batch_op.alter_column('organisation_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
