"""add funding milestones notified to programs

Revision ID: c517d003a957
Revises: fdebabbb5b07
Create Date: 2026-09-03 03:13:21.176339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c517d003a957'
down_revision = 'fdebabbb5b07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('programs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('funding_milestones_notified', sa.String(length=50), server_default='', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('programs', schema=None) as batch_op:
        batch_op.drop_column('funding_milestones_notified')
    # ### end Alembic commands ###
