"""add missing donation, delivery, settings, and chat tables

Revision ID: f849f5465974
Revises: aa12bb34cc56
Create Date: 2026-09-03 16:59:51.105869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f849f5465974'
down_revision = 'aa12bb34cc56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('donations')
    op.drop_table('program_memberships')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('program_memberships',
    sa.Column('membership_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('program_id', sa.INTEGER(), nullable=False),
    sa.Column('joined_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['programs.program_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('membership_id'),
    sa.UniqueConstraint('user_id', 'program_id')
    )
    op.create_table('donations',
    sa.Column('donation_id', sa.INTEGER(), nullable=False),
    sa.Column('program_id', sa.INTEGER(), nullable=False),
    sa.Column('donor_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('donor_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('amount', sa.NUMERIC(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.VARCHAR(length=10), nullable=True),
    sa.Column('donation_date', sa.DATE(), nullable=True),
    sa.Column('payment_method', sa.VARCHAR(length=50), nullable=True),
    sa.Column('anonymous', sa.BOOLEAN(), nullable=False),
    sa.Column('transaction_reference', sa.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['programs.program_id'], ),
    sa.PrimaryKeyConstraint('donation_id')
    )
    # ### end Alembic commands ###
