"""add user status and last_active_at

Revision ID: fdebabbb5b07
Revises: f543d6b23a7e
Create Date: 2026-09-03 02:31:11.518917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdebabbb5b07'
down_revision = 'f543d6b23a7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=30), server_default='Active', nullable=False))
        batch_op.add_column(sa.Column('last_active_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_active_at')
        batch_op.drop_column('status')
    # ### end Alembic commands ###
    # ### end Alembic commands ###
